<script lang="ts">
	import { page } from '$app/state';
	import { siteUrl } from '$lib/urls';
	import { getPage } from '$lib/docs/components';
	import { provideDocPageStatus } from '$lib/docs/doc-page-status.js';
	import { JsonLd } from '$lib/components';
	import { docArticleJsonLd } from '$lib/seo/structured-data';

	let { data } = $props();

	provideDocPageStatus(() => data.docPage.status);

	const loadedPage = $derived(getPage(data.docPage.filePath));
	const pageUrl = $derived(siteUrl('docs', data.docPage.href, page.url));
	const desc = $derived(data.docPage.description?.trim() ?? '');

	const showAiDisclosure = $derived(data.docPage.aiDisclosure === true);

	const articleJsonLd = $derived(
		docArticleJsonLd({
			title: data.docPage.title,
			description: desc || data.set.title,
			url: pageUrl,
			lastmod: data.docPage.lastmod
		})
	);

	const ogImageAbsolute = $derived(new URL('/og-image.jpg', page.url).href);
</script>

<svelte:head>
	<title>{data.docPage.title} – {data.set.title}</title>
	{#if data.docPage.description}
		<meta name="description" content={data.docPage.description} />
	{/if}
	<meta property="og:type" content="article" />
	<meta property="og:title" content={data.docPage.title} />
	<meta property="og:description" content={desc || data.set.title} />
	<meta property="og:url" content={pageUrl} />
	<meta property="og:image" content={ogImageAbsolute} />
	<meta name="twitter:card" content="summary_large_image" />
	<meta name="twitter:title" content={data.docPage.title} />
	<meta name="twitter:description" content={desc || data.set.title} />
	<meta name="twitter:image" content={ogImageAbsolute} />
</svelte:head>

<JsonLd data={articleJsonLd} />

<article class="doc-article text-txt-primary w-full min-w-0 leading-relaxed">
	{#if showAiDisclosure}
		<div class="ai-disclosure">
			<div class="ai-disclosure__icon" aria-hidden="true">
				<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
					<path d="m12 3-1.912 5.813a2 2 0 0 1-1.275 1.275L3 12l5.813 1.912a2 2 0 0 1 1.275 1.275L12 21l1.912-5.813a2 2 0 0 1 1.275-1.275L21 12l-5.813-1.912a2 2 0 0 1-1.275-1.275L12 3Z"/>
					<path d="m5 3 1 2.5L8.5 6 6 7 5 9.5 4 7 1.5 6 4 5.5 5 3Z" opacity="0.65"/>
					<path d="m19 17 1 2.5 2.5.5-2.5 1-1 2.5-1-2.5-2.5-1 2.5-1 1-2.5Z" opacity="0.65"/>
				</svg>
			</div>
			<div class="ai-disclosure__content">
				<span class="ai-disclosure__title">AI Disclosure:</span>
				<span class="ai-disclosure__text">This page was generated by an LLM and may contain inaccuracies. Hand-crafted documentation will be implemented over time on the road to 1.0</span>
			</div>
		</div>
	{/if}
	<loadedPage.Component />
</article>

<style>
	.ai-disclosure {
		display: flex;
		align-items: flex-start;
		gap: 0.875rem;
		padding: 1rem 1.25rem;
		margin-bottom: 2rem;
		background: color-mix(in oklab, var(--surface-raised) 35%, transparent);
		border: 1px solid var(--border-muted);
		border-radius: 0.75rem;
		backdrop-filter: blur(8px);
		transition: border-color 0.2s ease, box-shadow 0.2s ease;

		&:hover {
			border-color: var(--border-emphasis);
		}

		.ai-disclosure__icon {
			display: flex;
			align-items: center;
			justify-content: center;
			flex-shrink: 0;
			width: 1.75rem;
			height: 1.75rem;
			color: var(--text-secondary);
			background: color-mix(in oklab, var(--surface-sunken) 70%, transparent);
			border-radius: 0.5rem;
			border: 1px solid var(--border-muted);
			margin-top: 0.0625rem;
		}

		.ai-disclosure__content {
			font-size: 0.8125rem;
			line-height: 1.5;
		}

		.ai-disclosure__title {
			font-weight: 600;
			color: var(--text-primary);
			margin-right: 0.35rem;
		}

		.ai-disclosure__text {
			color: var(--text-secondary);
		}
	}
</style>
